version: "3"
services:
  clickhouse-example:
    container_name: clickhouse-example
    hostname: clickhouse-server-22.8.cnt
    image: clickhouse/clickhouse-server:22.8
    networks:
      -   lawyer-1
    ports:
      - "8123:8123"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./db/clickhouse/.docker-volume-clickhouse:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    environment:
      - CLICKHOUSE_USER=local_user # Имя пользователя
      - CLICKHOUSE_PASSWORD=147258 # Пароль пользователя
  app-example:
    build: docker-compose
    container_name: app-example
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-compose/git/auth.json:/root/.composer/auth.json
    networks:
      -   lawyer-1
  database_example:
    container_name: database_example
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=database_example
    volumes:
      - "./docker-compose/database_example:/var/lib/postgresql/data"
    networks:
      - lawyer-1
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin_container_tdsgn
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./.pgadmin:/root/.pgadmin
    networks:
      - lawyer-1
    ports:
      - ${PGADMIN_PORT:-5051}:80
    restart: unless-stopped

  redis-example:
    image: redis:latest
    container_name: 'redis-example'
    restart: always
    ports:
      -  6379:${REDIS_PORT}
    volumes:
      -   "./docker-compose/redis/redis.conf:/etc/redis/redis.conf"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - lawyer-1
  nginx-example:
    image: nginx:latest
    container_name: nginx-example
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    depends_on:
      - app-example
    networks:
      - lawyer-1

networks:
  lawyer-1:
    driver: bridge
